baseurl = "http://redskull.io/"
languageCode = "en-us"
title = "RedSkull.io"
destination = "/var/www/redskull.io/"
theme = "nova"
copyright = "<a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'><img alt='Creative Commons License' style='border-width:0' src='https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png' /></a><br /><span xmlns:dct='http://purl.org/dc/terms/' property='dct:title'>The RedSkull.io Website</span> by <a xmlns:cc='http://creativecommons.org/ns#' href='http://redskull.io/' property='cc:attributionName' rel='cc:attributionURL'>Bill Anderson</a> is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br />Based on a work at <a xmlns:dct='http://purl.org/dc/terms/' href='http://redskull.io/' rel='dct:source'>http://redskull.io/</a>."

[author]
    name = "Bill Anderson"
	email = "therealbill@me.com"

[[menu.main]]
    name = "Download RedSkull"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/therealbill/redskull/releases"
    weight = -200


[indexes]
  tag = "tags"

[taxonomies]
	category= "categories"
	tags= "tags"
